version: '3.8'

services:
    
    traefik:
        container_name: ${COMPOSE_PROJECT_NAME}_traefik
        image: traefik:2.5.2
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik/traefik.toml:/traefik.toml
            - ./traefik/logs:/logs

networks:
    default:
        name: ${COMPOSE_PROJECT_NAME}-local-net
        driver: bridge
